plugins:
  radon:
    enabled: true
    config:
      threshold: "C"  # Reports complexity > 10

  pep8:
    enabled: true
    config:
      max-line-length: 110


  markdownlint:
    enabled: true

  git-legal:
    enabled: true

  fixme:
    enabled: true