plugins:
  radon:
    enabled: true
    config:
      threshold: "C"  # Reports complexity > 10

  pep8:
    enabled: true
    checks:
      E731:  # Use of lambda
        enabled: false
      E501:  # line length
        enabled: false


  markdownlint:
    enabled: true

  git-legal:
    enabled: true

  fixme:
    enabled: true