language: python

os:
  - linux

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install -r requirements.txt
  - python setup.py install

  # For running tests
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - pytest --cov=sndata/

after_success:
  - coveralls
